---
title: Analysis of the Relationship between Industry and Skill with LinkedIn Data
output: html_document
---

LinkedIn is a business-oriented social network where people build their professional profiles. In this project, the correlation between an individual's industry and his skills was analyzed. The ultimate goal of this project is to build a job recommendation system based on a person's LinkedIn profile. My initial movement here is to infer a person's industry from his skills.   

# 1. Get Data
The code in "GetOnlineData.R" is used to connect to the LinkedIn API. However, LinkedIn has changed the availability of most of their API endpoints. Very limited profiles can be accessed. 

Fortunately, a LinkedIn data set was published in Reddit in the format of JSON files (http://www.reddit.com/r/dataisbeautiful/comments/25qjpz/how_many_employees_are_moving_between_companies_oc/chjvd0g). The code in "GetData.R" is used to download the compressed data and unzip them into JSON files. The total volume of the data is 4.29GB. 

# 2. Clean Data
The code in "CleanData.R" will read the JSON files and format them to be dataframes. The dataframe contains 5 columns and  
```{r, echo=FALSE}
plot(cars)
```
